### ISSUE TITLE
Une remarque sur VoltaireConnect

### ISSUE THREAD

**Issue by bphd** [SheatNoisette/VoltaireConnect#19]
Ouais, c'est stylé de sauter des évaluations nazes et tout, mais sinon Voltaire, c'est grave stylé à faire quand il n'y a pas la pression scolaire pour combler les lacunes de l'école défaillante. Le truc, c'est que c'est payant. À quand un fork du Projet Voltaire lui-même ? 

(Edité par SheatNoisette)

**Comment by SheatNoisette** [comment]
Cette extension (dépassée) était pour contester l'utilité du ProjetVoltaire dans le cadre d'entraînement obligatoire évalué par les écoles post bac. Il n'a nullement été fait dans le but de tricher.

**Comment by bphd** [comment]
> Il n'a nullement été fait dans le but de tricher.

J'ai jamais parlé de tricher, j'ai parlé de pouvoir s'entraîner de la même manière sans payer le projet voltaire

> l'utilité du ProjetVoltaire dans le cadre d'entraînement obligatoire évalué par les écoles post bac

`mais sinon Voltaire, c'est grave stylé à faire quand il n'y a pas la pression scolaire pour combler les lacunes de l'école défaillante`

**Comment by SheatNoisette** [comment]
Je vois, après c'est un tout autre problème. Je n'ai nullement l'envie de réaliser un clone du Projet Voltaire.

**Comment by bphd** [comment]
Avec tout ces repo voltaire vous vous êtes cassés la tête à dumper la bdd du site (la partie qui vaut de l'or) pour juste cliquer automatiquement dessus au lieu de valoriser la data en s'émacipant de ce site et cette entreprise

**Comment by SheatNoisette** [comment]
Cela ne dumpe pas la base de données !

**Comment by bphd** [comment]
Bah, j'ai fait le tour des projets et c'est pas mal ça. Ça s'appuie soit sur une sorte d'IA dont les données d'entraînement sont basiquement toutes les phrases du projet, soit ça fait une demande à un service externe qui eux même s'appuient sur des IA entraînées. Donc autant faire d'une pierre deux coups. Utiliser les phrases pour pwn le projet et à côté en proposer un clone qui n'aura ni la pression scolaire ni le paywall, une idylle de l'apprentissage du français, le projet sans ses défauts

**Comment by SheatNoisette** [comment]
Je ne comprends pas ce que vous souhaitez. À moins de faire une remarque sur le projet, je ferme l'issue.

**Comment by bphd** [comment]
Faire une version gratuite du projet

**Comment by SheatNoisette** [comment]
Je suis navrée, mais cela n'a nullement de rapport avec ce projet Open Source.
